language: bash

sudo: required


install:
  - docker build -t jasper .


script:
  - docker ps | grep -q jasper
  - docker login  -u rajhans953 -p rajhans.yadav
  - docker tag jasper rajhans953/jasper:latest
  - docker push rajhans953/jasper:latest
  
#  - pwd
#  - ls
#  - ls  /home/travis/build/rajhans995533/security/
#  

